feat: prebuild for vercel deployment

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,7 @@
-npx --no-install commitlint --edit
+if npx --no-install commitlint --edit; then
+  npx lint-staged
+  npm run build
+else
+  echo "Commit message validation failed. Skipping build."
+  exit 1
+fi
